# Generated by Django 3.2.3 on 2021-05-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag', '0002_auto_20210517_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.TextField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
