# Generated by Django 3.2.3 on 2021-05-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag', '0003_evento_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.CharField(max_length=60),
        ),
    ]
